### PR TITLE
Connectivity fixes, YouTube v3 support, trakt.tv fixed, and minor CSS changes

### PR DESCRIPTION
**Pull request by pdille**
Here are all my commits for the Chrome extension. Same as is found in my pull request for FireFox, with the addition of course of any Chrome specific changes.

### CODE REVIEW

**Comment by sergiorbp** [comment]
I've been waiting for YouTube v3 support =) How can I get this update?

**Comment by joshuahiggins** [comment]
@sergiorbp You can either clone @pdille's fork and manually install it into Chrome or wait for @Moussa to review and merge this pull request and push a new build to the Chrome plugin. Hopefully it happens soon!

**Comment by sergiorbp** [comment]
@joshuahiggins THANKS!! but.. sorry.. github newbie here.. How can I clone @pdille's fork/branch? I only see @Moussa's master and branches both in the web and Mac app. 
I also tried:
`git remote add pdille git@github.com:pdille/Transmogrify-for-Plex-chrome.git`
but got:
`fatal: Not a git repository (or any of the parent directories): .git`
Can you please help? Cant wait to get my hands on this update.

**Comment by sergiorbp** [comment]
So I figure that part out. I had to go into @pdille's  profile and fork it from there. hmm.. Who would have thought it was that easy.. :P ...but...  I was not able to get it going in chrome. After uninstalling the previous release, packing @pdille's version as a "crx" and adding it to chrome it doesn't work.., I can access the Transmogrify options page but it has no effect in Plex (no info overlay whatsoever).
I guess I'll have to wait for the official release like the rest of us newbies.. :/
Thanks @joshuahiggins for your earlier response and @pdille for the update, looking forward to it.

**Comment by pdille** [comment]
Did you include all the appropriate API keys? They aren't part of the git repository. 

So yeah, I'd wait for @Moussa to make an official release. I hope he's still around.

**Comment by sergiorbp** [comment]
@pdille Funny that you mention that... I did notice a "Private key file (optional):" field when packing the extension. Is that it?? Although I have no idea where to get the key LOL Can you help?

I too wonder where @Moussa  is, he also disappeared from the Plex forums. hmm..

**Pull request merged**
